name: tapjoy
description: "A new Flutter plugin project."
version: 0.0.1+1
homepage: https://github.com/uprise-fin/flutter-plugins

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.tapjoy
        pluginClass: TapjoyPlugin
      ios:
        pluginClass: TapjoyPlugin

repository: https://github.com/uprise-fin/flutter-plugins
